### PR TITLE
rh-che #675 Changes in che tenant quotas required for increasing memory limits to 3GB for workspace pods

### PR DESCRIPTION
**Pull request by ibuziuk**
Related issue - https://github.com/redhat-developer/rh-che/issues/675

New quotas are expected to be the following once PR is merged

image

Resulting quota yml:

```
---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: LimitRange
  metadata:
    labels:
      app: fabric8-tenant-che-quotas-oso
      provider: fabric8
      version: 2.0.0-SNAPSHOT
      group: io.fabric8.tenant.packages
    name: resource-limits
  spec:
    limits:
    - max:
        cpu: 6000m
        memory: 3Gi
      min:
        cpu: 29m
        memory: 150Mi
      type: Pod
    - default:
        cpu: "1"
        memory: 512Mi
      defaultRequest:
        cpu: 60m
        memory: 307Mi
      max:
        cpu: 6000m
        memory: 3Gi
      min:
        cpu: 29m
        memory: 150Mi
      type: Container
    - max:
        storage: 1Gi
      min:
        storage: 1Gi
      type: PersistentVolumeClaim
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    labels:
      app: fabric8-tenant-che-quotas-oso
      provider: fabric8
      version: 2.0.0-SNAPSHOT
      group: io.fabric8.tenant.packages
    name: compute-resources
  spec:
    hard:
      limits.cpu: "6"
      limits.memory: 3Gi
    scopes:
    - NotTerminating
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    labels:
      app: fabric8-tenant-che-quotas-oso
      provider: fabric8
      version: 2.0.0-SNAPSHOT
      group: io.fabric8.tenant.packages
    name: compute-resources-timebound
  spec:
    hard:
      limits.cpu: "6"
      limits.memory: 3Gi
    scopes:
    - Terminating
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    labels:
      app: fabric8-tenant-che-quotas-oso
      provider: fabric8
      version: 2.0.0-SNAPSHOT
      group: io.fabric8.tenant.packages
    name: object-counts
  spec:
    hard:
      persistentvolumeclaims: "2"
      replicationcontrollers: "20"
      secrets: "20"
      services: "5"

```

### CODE REVIEW

**Comment by fabric8cd** [comment]
PR now available for testing: https://openshift.io/_profile/_tenant?cheVersion=PR-vbee94e1-1&mavenRepo=https://nexus.cd.test.fabric8.io/content/repositories/staging

**Comment by ibuziuk** [comment]
@riuvshin @kbsingh @jfchevrette please review if new limits looks good.

**Comment by riuvshin** [comment]
cc: @pbergene

**Comment by pbergene** [comment]
There is agreement to use the 3G for che workspaces, so that's fine by me.  My understanding is that the limits formula  should accommodate requesting 3G with 6000m. Would like to validate with  @jfchevrette  that we get this reflected in our scale docs.

**Comment by ibuziuk** [comment]
>  My understanding is that the limits formula should accommodate requesting 3G with 6000m.

@pbergene that's my understanding as well - https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/794#note_233031

**Comment by jfchevrette** [comment]
LGTM

**Pull request merged**
