### PR TITLE
add CI PR comments for YAML version

### PR DESCRIPTION
**Pull request by rawlingsj**

### CODE REVIEW

**Comment by fabric8cd** [comment]
snapshot YAML now available: `CHE_VERSION=vcc0d923-SNAPSHOT` `YAML_MVN_REPO=http://nexus.cd.k8s.fabric8.io/content/repositories/snapshots`

**Comment by fabric8cd** [comment]
snapshot YAML now available: `CHE_VERSION=vedd9856-SNAPSHOT` `YAML_MVN_REPO=http://nexus.cd.k8s.fabric8.io/content/repositories/snapshots`

**Comment by fabric8cd** [comment]
snapshot YAML now available: `CHE_VERSION=vf51d94e-SNAPSHOT` `YAML_MVN_REPO=http://nexus.cd.k8s.fabric8.io/content/repositories/snapshots`

**Comment by rawlingsj** [comment]
[skip release]

**Pull request merged**
