### PR TITLE
rh-che #404: Adding package for multi-tenant che with workspace PVC

### PR DESCRIPTION
**Pull request by ibuziuk**
Defines the workpsace PVC that should be configured in user namespace for multi-tenant che support

### CODE REVIEW

**Comment by fabric8cd** [comment]
PR now available for testing: https://openshift.io/_profile/_tenant?cheVersion=PR-v22adacd-1&mavenRepo=https://nexus.cd.test.fabric8.io/content/repositories/staging

**Comment by ibuziuk** [comment]
@l0rd sounds good. Thanks for review

**Comment by ibuziuk** [comment]
PR has been updated

**Comment by fabric8cd** [comment]
PR now available for testing: https://openshift.io/_profile/_tenant?cheVersion=PR-v4393497-2&mavenRepo=https://nexus.cd.test.fabric8.io/content/repositories/staging

**Comment by ibuziuk** [comment]
@aslakknutsen FYI, artifacts with workspace PVC for multi-tenancy are now available on central - http://central.maven.org/maven2/io/fabric8/tenant/packages/fabric8-tenant-che-mt/

**Pull request merged**
