### PR TITLE
WIP: getting che to work on fabric8

### PR DESCRIPTION
**Pull request by jstrachan**

### CODE REVIEW

**Comment by fabric8cd** [comment]
PR now available for testing: https://openshift.io/_profile/_tenant?cheVersion=PR-v2760974-2&mavenRepo=https://nexus.cd.test.fabric8.io/content/repositories/staging

**Comment by fabric8cd** [comment]
PR now available for testing: https://openshift.io/_profile/_tenant?cheVersion=PR-vf187586-4&mavenRepo=https://nexus.cd.test.fabric8.io/content/repositories/staging

**Comment by fabric8cd** [comment]
PR now available for testing: https://openshift.io/_profile/_tenant?cheVersion=PR-vf86162f-5&mavenRepo=https://nexus.cd.test.fabric8.io/content/repositories/staging

**Comment by ibuziuk** [comment]
Closing as outdated

**Pull request closed without merging**
