### PR TITLE
Increasing RAM limits to 2.5 Gi

### PR DESCRIPTION
**Pull request by ibuziuk**

### CODE REVIEW

**Comment by fabric8cd** [comment]
PR now available for testing: https://openshift.io/_profile/_tenant?cheVersion=PR-vf115c80-1&mavenRepo=https://nexus.cd.test.fabric8.io/content/repositories/staging

**Comment by fabric8cd** [comment]
PR now available for testing: https://openshift.io/_profile/_tenant?cheVersion=PR-v9beaeb3-2&mavenRepo=https://nexus.cd.test.fabric8.io/content/repositories/staging

**Comment by ibuziuk** [comment]
image
tested on prod and new limmits are set correctly now

**Comment by l0rd** [comment]
Cool @ibuziuk now do use that extra memory for the workspaces we should update https://github.com/redhat-developer/rh-che/blob/multi-tenant-rh-che/openshift/rh-che.config.yaml#L22

**Comment by ibuziuk** [comment]
@l0rd sure. 
BTW, do you think we should increase RAM for ws-agent. 
As I recall che is uses 2Gi for it by default, because with 1.5 it fails in some cases cc: @eivantsov ?
Or for now lets update only workspace RAM in general so that for mvn we would have ~ 1200 Mb

**Comment by l0rd** [comment]
@ibuziuk I would leave the RAM for wsagent as it is right now. It looks like wsagent is working fine on OSIO right now.

**Comment by ibuziuk** [comment]
@l0rd ok sounds good

**Comment by ibuziuk** [comment]
PR for multi-tenant template - https://github.com/redhat-developer/rh-che/pull/443

**Pull request merged**
